Numpy is a Linear Algebra Library for Python.

In [1]:
!pip install numpy

In [2]:
import numpy as np

### Numpy Arrays

Main way that we will use Numpy

* 1 Dimensional Array


* 2 Dimensional Array or Matrix

Creating Array

* using list

In [3]:
lst = [1,2,3]
type(lst)

list

In [4]:
f = np.array(lst)

f

array([1, 2, 3])

In [5]:
type(f)

numpy.ndarray

#### Built In Methods

#### arange 

Returns evenly spaced values in a given interval

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### zeros and ones

Generates arrays of zeros and ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### linspace

Returns evenly spaced numbers over a specified interval

In [12]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### Random

#### rand
Creates array of given shape and populates it with random samples from a uniform distribution over 0 - 1.

In [13]:
np.random.rand(10)

array([0.81948598, 0.69712892, 0.55876533, 0.64517002, 0.80704509,
       0.75184961, 0.33644078, 0.91713598, 0.87482026, 0.85291589])

#### randn

Returns a sample from normal distribution

In [14]:
np.random.randn(2)

array([-0.24848124,  1.96139158])

In [15]:
np.random.randn(5,5)

array([[ 0.38008325, -0.62977983, -0.66778184, -0.22273929, -0.60951493],
       [-0.05239602,  1.10430219, -0.03994493, -1.33320969, -0.56649684],
       [-0.14826093, -0.20028046,  2.07439775,  0.43592522,  0.34896101],
       [-0.31802744, -0.88693331, -0.08269345,  0.09784833,  0.87868877],
       [-0.34564724,  0.35062182,  0.28907491, -0.09721902, -0.54851821]])

#### randint

Return random integers from low to high

In [16]:
np.random.randint(1,100)

72

In [17]:
np.random.randint(1,100,10)

array([26, 17, 10, 42, 90, 19, 56,  3, 62, 92])

#### Array Attributes and Methods

In [18]:
arr = np.arange(25)

ranarr = np.random.randint(0,50,10)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr

array([21, 18, 43, 27, 13,  8, 31, 45, 16, 10])

#### Reshape

Returns an array containing the same data with new shape

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
ranarr

array([21, 18, 43, 27, 13,  8, 31, 45, 16, 10])

In [24]:
ranarr.max()

45

In [25]:
ranarr.min()

8

In [26]:
ranarr.argmax()

7

In [27]:
ranarr.argmin()

5

#### Indexing of np arrays

In [38]:
ranarr

array([21, 18, 43, 27, 13,  8, 31, 45, 16, 10])

In [29]:
ranarr[1]

18

In [30]:
ranarr.shape

(10,)

In [36]:
rarr = ranarr.reshape(5,2)
rarr

array([[21, 18],
       [43, 27],
       [13,  8],
       [31, 45],
       [16, 10]])

In [37]:
rarr[3][1]

45

In [44]:
rarr[3,1]

45

#### Selection

In [39]:
arr = np.arange(1,11)

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [43]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# Great Job !